### ISSUE TITLE
Last updated does not render on all pages

### ISSUE THREAD

**Issue by staghouse** [mtgjson/mtgjson-website#100]
The last updated marker at the bottom of the pages does not render on all pages (VuePress bug?).

Question is: Should it exist? Its possible that these dates could be confusing since we do builds based on the python app releases.

**Comment by ZeldaZach** [comment]
The website gets updated more often than the Repo, so I'm fine with having them. I thought it updates based on what pages are re-compiled? In that case, pages might have different dates on them. Check that maybe?
