### ISSUE TITLE
Create Lazy loading for large download data like Individual Sets and Decks

### ISSUE THREAD

**Issue by staghouse** [mtgjson/mtgjson-website#108]
Allow the download seconds for Individual Sets and Decks to have lazy loading to prevent render lag.

**Comment by staghouse** [comment]
Because the fetch calls return all the data and is not on an API endoint with options, RESTfullness is out, We would gain no perf increase and just be adding pagination in items that are sortable. To me, its a major feature not worth going after.

**Comment by ZeldaZach** [comment]
Not worth it then.
