### ISSUE TITLE
Please add my mobile app link

### ISSUE THREAD

**Issue by ChrisFromCanada** [mtgjson/mtgjson-website#112]
Please add my link (https://www.magictradebinder.com/) , as I use MTGJSON extensively while developing the mobile app Magic Trade Binder (Android and soon to be iOS).

Thanks!
-Chris
![logo with padding](https://user-images.githubusercontent.com/37028808/56152387-86e3b280-5f81-11e9-9283-ae7973ca0abf.png)

**Comment by ZeldaZach** [comment]
Dupe
