### ISSUE TITLE
Please add a link to my mobile app (Magic Trade Binder)

### ISSUE THREAD

**Issue by ChrisFromCanada** [mtgjson/mtgjson-website#113]
Please add my link (https://www.magictradebinder.com/) , as I use MTGJSON extensively while developing the mobile app Magic Trade Binder (Android and soon to be iOS).

Thanks!
-Chris
![logo with padding](https://user-images.githubusercontent.com/37028808/56096179-bbd50400-5eb2-11e9-8319-b8a4d19e8464.png)

**Comment by staghouse** [comment]
Merged
