### ISSUE TITLE
no rss feed available to follow updates

### ISSUE THREAD

**Issue by tooomm** [mtgjson/mtgjson-website#14]
Unlike v3 there is no newsfeed available for subscribing to new releases and changes.

**Comment by tooomm** [comment]
How do you expect people to stay updated?
Is there any reliable, alternative channel than going to the webpage and check manually?

RSS could be used for a lot of stuff like feed readers, they could start triggers and could be used with services like ifttt and they are generally easy to consume and process automatically etc.

**Comment by ZeldaZach** [comment]
I'll have to look into something like this then... Open to help

**Comment by ancestral** [comment]
In order to make use good of the feeds, we would need to re-work the changelog from a singular page to a conglomeration of posts. This could be done, but would take some time to do.

**Comment by ZeldaZach** [comment]
I added an atom feed (https://mtgjson.com/atom.xml) but I think this is as good as it'll get
