### ISSUE TITLE
version in header links to non-existant changelog entry

### ISSUE THREAD

**Issue by tooomm** [mtgjson/mtgjson-website#145]
due to wrong date

**Comment by ZeldaZach** [comment]
It came down to I ran my spoiler season poorly. Will try again next time with new knowledge. This won’t be fixed until the next release most likely.

**Comment by tooomm** [comment]
Same same but different:
![header link](https://user-images.githubusercontent.com/9874850/56866155-734f3780-69d6-11e9-8177-9eae6ecfd308.png)

Header still links to 4.3.2 instead 4.4.0

**Comment by ZeldaZach** [comment]
Force refresh the page. Not sure why that one part lags out so much

**Comment by tooomm** [comment]
A reload without cache (`Ctrl + F5`) did change nothing.

**Comment by tooomm** [comment]
A day and several refreshes later I still get 4.3.2 displayed as seen in the screen.

<br>

Any idea why this isn't updating @staghouse?
>Zach: Not sure why that one part lags out so much
