### ISSUE TITLE
New data added

### ISSUE THREAD

**Issue by ZeldaZach** [mtgjson/mtgjson-website#156]
New fields added w/ example (These are to each card object)

Future note: The dates are wrong right now, but they will be Sundays in all offical releases. And we will re-build on Sundays for deployment with a new version date of some kind. Still figuring out how I want to call the version#/date

```
"mtgstocksId": 40272,
"prices": {
                "paper": {
                    "2019-01-23": 0.25,
                    "2019-01-30": 0.25,
                    "2019-02-06": 0.25,
                    "2019-02-13": 0.25,
                    "2019-02-20": 0.26,
                    "2019-02-27": 0.26,
                    "2019-03-06": 0.27,
                    "2019-03-13": 0.29,
                    "2019-03-20": 0.27,
                    "2019-03-27": 0.27,
                    "2019-04-03": 0.28,
                    "2019-04-10": 0.29,
                    "2019-04-17": 0.29,
                    "2019-04-24": 0.28
                }
            },
```

Also added `mtgstocks` to purchaseUrl feed

**Comment by staghouse** [comment]
Just out of curiosity, "paper" as a nested key is because you foresee a future with a another key added?

**Comment by ZeldaZach** [comment]
Yep; mtgo, mtga, paper_foil, etc are future values
