### ISSUE TITLE
version number scheme

### ISSUE THREAD

**Issue by tooomm** [mtgjson/mtgjson-website#172]
Following the former pattern, `4.4.0` should only be `4.4`. (Same for 4.3 btw)
It's also `"version": "4.4.0"` in the meta data of the mtgjson file.

I get that that always 3 digits are used as full version tag, and cutting the 0-patch ending on the website in the changelog is probably done to highlight new feature releases.
It really helps and is a nice feature in the menu. 👍 

Also linking https://github.com/mtgjson/mtgjson-website/issues/145#issuecomment-487386723

**Comment by ZeldaZach** [comment]
I'm happy with the trailing zero personally, and it doesn't make a different in the end. Hope you understand.

**Comment by tooomm** [comment]
>I'm happy with the trailing zero personally

That's fine. But then please add it to 4.0, 4.1 and 4.2 as well 👍

**Comment by tooomm** [comment]
>I'm happy with the trailing zero personally

That's fine. But then please add it to 4.0, 4.1 and 4.2 as well 👍 

![changelog menu](https://user-images.githubusercontent.com/9874850/56869189-98a36c00-69fd-11e9-896f-be362ee35346.png)
