### ISSUE TITLE
better example for set name translations

### ISSUE THREAD

**Issue by tooomm** [mtgjson/mtgjson-website#187]
https://www.mtgjson.com/structures/translations/

Use a different example where Chinese Traditional and Chinese Simplified are not identical:
- Chinese Simplified | string | "效忠拉尼卡" | Translation in Chinese Simplified.
- Chinese Traditional | string | "效忠拉尼卡" | Translation in Chinese Traditional.

**Comment by staghouse** [comment]
Can you provide the proper variation?

**Comment by tooomm** [comment]
Here are some examples from AllSets.json:
(Notify the weird `『』` signs which frame several japanese translations. That looks wrong....

        "translations": {
            "Chinese Simplified": "乙太之乱",
            "Chinese Traditional": "乙太之亂",
            "French": "La révolte éthérique",
            "German": "Äther-Rebellion",
            "Italian": "Rivolta dell’Etere",
            "Japanese": "『霊気紛争』",
            "Korean": "에테르 봉기",
            "Portuguese (Brazil)": "Revolta do Éter",
            "Russian": "«Эфирный Бунт»",
            "Spanish": "La revuelta del éter"

        "translations": {
            "Chinese Simplified": "启示录",
            "Chinese Traditional": "啟示錄",
            "French": "Apocalypse",
            "German": "Apokalypse",
            "Italian": "Apocalisse",
            "Japanese": "アポカリプス",
            "Korean": "파멸",
            "Portuguese (Brazil)": "Apocalipse",
            "Russian": "Apocalypse",
            "Spanish": "Apocalipsis"


        "translations": {
            "Chinese Simplified": "再战赞迪卡",
            "Chinese Traditional": "再戰贊迪卡​",
            "French": "La bataille de Zendikar",
            "German": "Kampf um Zendikar​",
            "Italian": "Battaglia per Zendikar​",
            "Japanese": "『戦乱のゼンディカー』",
            "Korean": "젠디카르 전투",
            "Portuguese (Brazil)": "Batalha por Zendikar​",
            "Russian": "Битва за Зендикар​",
            "Spanish": "La batalla por Zendikar​"


        "translations": {
            "Chinese Simplified": "天神创生",
            "Chinese Traditional": "天神創生",
            "French": "Créations divines",
            "German": "Kinder der Götter",
            "Italian": "Figli degli dei",
            "Japanese": "『神々の軍勢』",
            "Korean": "신들의 피조물",
            "Portuguese (Brazil)": "Nascidos dos Deuses",
            "Russian": "Порождения Богов",
            "Spanish": "Nacidos de los Dioses"

**Comment by staghouse** [comment]
The above is unrelated to this issue. That data would be coming from the Python app. You'll want to post the issue there I believe.

**Comment by tooomm** [comment]
Oh yes, that part should go there. 👍

**Comment by staghouse** [comment]
Addressed via #196
