### ISSUE TITLE
The Team page looks weird

### ISSUE THREAD

**Issue by ancestral** [mtgjson/mtgjson-website#190]
It appears some formatting weirdness is making its way through onto the page. Happens in every browser and device I own, desktop and mobile.

<img width="606" alt="image" src="https://user-images.githubusercontent.com/735024/58743491-2527bc80-83f8-11e9-8f5c-210c5e82fdae.png">

**Comment by staghouse** [comment]
Fix #191

**Comment by ancestral** [comment]
Still looks weird.

**Comment by staghouse** [comment]
The fix is referenced in the MR but there has not been a build yet so you will not see the fix on production.

Going forward for clarity I will keep issues open until build occurs that way we can properly QA.

**Comment by ancestral** [comment]
Good work! Looks good now.
