### ISSUE TITLE
Stress/mark unreleased sets on webpage

### ISSUE THREAD

**Issue by tooomm** [mtgjson/mtgjson-website#205]
In the list of sets you can download, not yet released sets ("Spoiler") show no hint that they are subject to change and only contain a fraction of the cards yet.
I would like to see a `Spoiler` tag there for example. Based on the release date of the set and when the last mtgjson version is build for example. Maybe checking the card count against the set size is an option too?

**Comment by ZeldaZach** [comment]
I like this idea; Easy to do, just look for what's before 'Release' date

**Comment by tooomm** [comment]
Implemented in #207. This looks really nice @staghouse

How did you solve it? Will it compare the time on build time of the page?

**Comment by staghouse** [comment]
It currently compares to current date time @tooomm
