### ISSUE TITLE
Documentation missing "Count"

### ISSUE THREAD

**Issue by ZeldaZach** [mtgjson/mtgjson-website#214]
Count field is used _only_ in decks, which indicates how many copies of a card there are. We should identify this in the docs.

**Comment by staghouse** [comment]
Which of these structures does this refer to?

Individual Deck -> A singular compiled deck
DecksList -> Compiled list of all decks
decks -> Structure describing a deck from DecksList

**Comment by ZeldaZach** [comment]
Inside a deck, it's a card object with an extra field. {name: ..., id: ..., count: INT}
