### ISSUE TITLE
SQLITE download has no data, only headers

### ISSUE THREAD

**Issue by ancestral** [mtgjson/mtgjson-website#223]
SQLITE download has no data, only headers

**Comment by ZeldaZach** [comment]
Known issue. I broke it last week. Fixed it today. Will re up tomorrow.

**Comment by ancestral** [comment]
Would it be okay to leave this open until the fix is live? That way we can track it and verify the issue is resolved.

Thanks!

**Comment by ancestral** [comment]
OK looks good now. Thanks!
