### ISSUE TITLE
DesktopComp

### ISSUE THREAD

**Issue by ZeldaZach** [mtgjson/mtgjson-website#231]
Add https://github.com/nicho92/MtgDesktopCompanion

**Comment by ZeldaZach** [comment]
Also add http://metadeck.me/

**Comment by staghouse** [comment]
Included in #233

**Comment by staghouse** [comment]
CLose #233

**Comment by nicho92** [comment]
Hey guys, thanks a lot for adding my MTGCompanion project. I'm very proud :) . Can i just suggest to change website url please ? 

Replace -> https://github.com/nicho92/MtgDesktopCompanion   by https://nicho92.github.io/MtgDesktopCompanion/

**Comment by tooomm** [comment]
Feel free to open a PR next time @nicho92! (https://github.com/mtgjson/mtgjson-website/pull/254)

**Comment by nicho92** [comment]
> Feel free to open a PR next time @nicho92! (#254)

I did not dare :sweat_smile: Thanks again ;)
