### ISSUE TITLE
Do rebuilds contain `edhrecRank` updates?

### ISSUE THREAD

**Issue by tooomm** [mtgjson/mtgjson-website#241]

**Comment by ZeldaZach** [comment]
Yes, they do. Not sure why a ticket is needed here.

**Comment by tooomm** [comment]
That info is then missing in the website description of rebuilds. I added it.
Was in a hurry this morning, so I simply dropped the question here.

**Comment by ZeldaZach** [comment]
Ahh, gotcha. FYI we chat about all issues on Discord, especially fixes for them. Please do join us :)
