### ISSUE TITLE
Invalid Links in Shields

### ISSUE THREAD

**Issue by Macro303** [mtgjson/mtgjson-website#255]
#### Steps to reproduce
Hover/Follow the 'Maintained' and 'Licence' shields in the README

#### What is expected?
That they point to the [MTGJson-Website Repo](https://github.com/mtgjson/mtgjson-website)

#### What is actually happening?
They're pointing to [Windfish-App Repo](https://github.com/staghouse/windfish-app)

**Comment by ZeldaZach** [comment]
README fixes needed
