### ISSUE TITLE
Add support for minified JSON dumps and CSV (Logic)

### ISSUE THREAD

**Issue by staghouse** [mtgjson/mtgjson-website#264]
### Is your feature request related to a problem? Please describe.

There is a desire for more compressed or usable files

### Describe the solution you'd like

More buttons!

### Describe, if any, alternatives you've considered

Just need to increase the logic to handle more types of 

### Additional context

Try to compile the components down to a single download component

**Comment by staghouse** [comment]
To add more color to this, I really want to reduce the logic we have for buttons so it handle all formats. Right now, we say "here are the formats for this page, iterate and show them and show the filters". Instead, I rather say "here is all the page name, here is the formats, here is the type of files, reduce the formats and show the filters"

**Comment by ZeldaZach** [comment]
Minified dumps are now the default. CSV is a separate issue.
