### ISSUE TITLE
Legalities page

### ISSUE THREAD

**Issue by APrettyCoolProgram** [mtgjson/mtgjson-website#265]
#### MTGJSON Version: 4.X.X
4.5.0-rebuild.1
#### Description of Bug:
The legalities page (https://mtgjson.com/structures/legalities/) is missing "Future".

**Comment by ZeldaZach** [comment]
future means "will be legal in standard after the next rotation"

**Comment by ZeldaZach** [comment]
(Future is a key, not a value) this changed at some point upstream.
