### ISSUE TITLE
Legalities page ambiguity

### ISSUE THREAD

**Issue by harbingerofme** [mtgjson/mtgjson-website#266]
The page currently reads:

> Future is used for a revision of the format in which the card will be legal soon. If the format is not listed, it is assumed the card is not legal in that format.)
>If a card is "not legal", it will be omitted from the data.

The _it_ in the last sentence is ambiguous between card and property while the property is clearly meant. 
After all, it could be reasonable for an user to assume that mtgjson doesn't list cards that aren't legal in any format.

**Comment by ZeldaZach** [comment]
Future is being re-assigned as a key over a value (See #265) but the page should read, in essence, "Cards that are not legal in a format will not have that format key defined"
