### ISSUE TITLE
Add version.atom

### ISSUE THREAD

**Issue by ZeldaZach** [mtgjson/mtgjson-website#273]
A member of the community has asked us to re-add RSS feeds to better suit their needs of when to update. The feed should incorporate the same information found in `version.json` 

This doesn't have to be overly complicated, but enough so our users know what's up.

**Comment by tooomm** [comment]
It could have the meta data for every version as well as the changelog information, or should link to that at least. 

Normally a feed contains more than just one entry.

**Comment by staghouse** [comment]
Sounds like something we will have to roll our own of

**Comment by staghouse** [comment]
Thinking about implementation, I want to standardize the entire "feeds" logic. Right now we have `atom.xml` but this isnt very descriptive so i would rename that to `site.atom`. Here is a flow of what I am thinking:

### Node

Create:
`/site.atom`
`/site.rss`
`/site.json`

### Python or Node

Create:
`/versions.json`

### Deployment

1. Create `/feeds`
2. Move files:
    - `/site.atom` => `/feeds/site.atom`
    - `/site.rss` => `/feeds/site.rss`
    - `/site.json` => `/feeds/site.json`
    - `/versions.json` => `/feeds/versions.json`

**Comment by tooomm** [comment]
What about `version.atom` or `mtgjson.atom`?

**Comment by ZeldaZach** [comment]
I'm only looking for changelog.atom which updates whenever we make a change to the changelog page with a new version. Nothing more required for the time being.

**Comment by staghouse** [comment]
Also, to be clear, this ticket is titled "re-add RSS" as if we dont have any already. We do have atom.xml which is the `atom` file feed for the entire site. We can very easily turn on actual RSS and JSON feeds with names of our choice.
