### ISSUE TITLE
Link Cards Info for MTG in list of supporters

### ISSUE THREAD

**Issue by dbottillo** [mtgjson/mtgjson-website#274]
Hi,
I've been using your dataset to power this android application and it would be nice if you could include it in the supporter list.

Let me know if you need an icon and if yes, which size.

Link: https://play.google.com/store/apps/details?id=com.dbottillo.mtgsearchfree

Thanks!

**Comment by ZeldaZach** [comment]
The logo on the app store looks fine, but SVGs are also accepted. Feel free to upload if you'd like

**Comment by dbottillo** [comment]
![mtg_cards_icon_512](https://user-images.githubusercontent.com/485717/64130597-46af9000-cdbb-11e9-8406-5ebdeea38779.png)
is this good enough?

**Comment by ZeldaZach** [comment]
Works for me 😄
