### ISSUE TITLE
Block field not marked as optional

### ISSUE THREAD

**Issue by Draghi** [mtgjson/mtgjson-website#287]
Currently writing an application off of the AllSetFiles data and noticed that the Block tag in the Set structure appears to be optional, however this is not reflected on the website:
https://mtgjson.com/structures/set/

Hopefully this is the right place to report it 😅

**Comment by ZeldaZach** [comment]
Good spotting! I'll fix this up tomorrow

**Comment by ZeldaZach** [comment]
Fixed in a00a11ac7b626710451310d3ff170d2019214453
