### ISSUE TITLE
Missing Property Information

### ISSUE THREAD

**Issue by Macro303** [mtgjson/mtgjson-website#288]
### Steps to reproduce
Go to [SetList](https://mtgjson.com/files/set-list/) and the 'type' field is missing from the list of properties.

### What is expected?
The Json file has a 'type' field for each set in the SetList, so either it should be removed from the Json file or added to the documentation.

**Comment by ZeldaZach** [comment]
Fixed in a00a11ac7b626710451310d3ff170d2019214453
