### ISSUE TITLE
Legalities data structure

### ISSUE THREAD

**Issue by lutangar** [mtgjson/mtgjson-website#291]
The natural data structure for the `legalities` property should be a map instead of an array.

For example, in Scryfall, it's actually a map: 
```
// [...]
"legalities": {
    "standard": "not_legal",
    "future": "not_legal",
    "historic": "not_legal",
    "modern": "not_legal",
    "legacy": "banned",
    "pauper": "not_legal",
    "vintage": "restricted",
    "penny": "not_legal",
    "commander": "legal",
    "brawl": "not_legal",
    "duel": "banned",
    "oldschool": "not_legal"
},
// [...]
```
> https://api.scryfall.com/cards/e8e7916c-f39a-48a0-a47d-7e83ebf028fa?format=json&pretty=true

But in MTGJSON it's becoming an array.
> https://mtgjson.com/structures/legalities/

**Comment by ZeldaZach** [comment]
Do note that if a card is not legal, we intentionally do not display that legality.

Can we also confirm all of our map structures are accurately portrayed as such?

**Comment by lutangar** [comment]
> Can we also confirm all of our map structures are accurately portrayed as such?

Apparently, `prices` on the other hand, is correctly reported as an `object`.
And the *Parent property type* of prices is `object(anonymous object)`.
> https://mtgjson.com/structures/prices/

But on `legalities` the *Parent property type* is  reported as `array(object)`.

**Comment by ZeldaZach** [comment]
🤔 If you'd like to help fix up some of our documentation, it's all hosted in this repo in `docs/.vuepress` Otherwise we'll have to do a full review at some point to ensure we're accurate
