### ISSUE TITLE
Change Download Files Directory

### ISSUE THREAD

**Issue by omfgitsmark** [mtgjson/mtgjson-website#303]
Currently all downloadable files are stored in the `/json/` directory, even though some of the files are not JSON.

This should probably be changed to `/files/`, or `/downloads/` to be more inclusive to all files offered. (We don't want to hurt any file's feelings and maintain our politically correct status)

If we want to go even further it could be structured by each type, For example:
`/files/json/AllPrintings.json`, `/files/csv/cards.csv`, `/files/sql/AllPrintings.sql`, etc.

**Comment by ZeldaZach** [comment]
Done.
