### ISSUE TITLE
Add Mark to Team

### ISSUE THREAD

**Issue by ZeldaZach** [mtgjson/mtgjson-website#305]
Mark has been added to the team full time. He deserves to be on the homepage (above Ancestral)

**Comment by omfgitsmark** [comment]
I'd like to thank my mom, and Jason, and everyone who believed in me! 

If you ask me to write something you know I'm gonna go overboard, especially when I get to write about my favorite subject: me. So sorry if this is a bit much:

> Mark is an old man obsessed with learning anything he can. A self-proclaimed jack of all trades, yet master of none. He spends his time gaming, writing, farming, and cuddling with his dogs.  Some might say he has always been working on the MTGJSON project since the beginning of time...but they would be wrong because he actually joined in 2019. He is mostly kept around for comedic relief.

![mark](http://249d.com/images/sissyface_250x250.png)
