### ISSUE TITLE
Have a page which explains the current build schedule and update/deploy routines

### ISSUE THREAD

**Issue by tooomm** [mtgjson/mtgjson-website#326]
### Describe the solution you'd like
Have a new page which tells about daily builds and which data is updated.
There can be some information be found in the changelog section, but those will hide over time.
Zach mentioned weekly builds once, which I have no idea what they do.

Also the version pattern could be explained and when it gets updated.
Because only rebuilding doesn't change the version number, but appends a date (at least for the daily update - prices only according to the hint in the changelog?)

But also not every content update on card data or new sets does change the version number. Only code changes, new fields etc. do.

Explain that to the user.

---

The website has this sentence on the startpage:
`JSON builds for new card prices go live daily, and weekly builds are scheduled to be performed at 4PM EST.`
and this one on the changelog page:
`Versions marked with dates are rebuilds and fully backwards compatible with the release, and contain updates for fields that require more frequent updating (e.g. prices and EDH Rank), as well as data improvements.`
It's not quite clear though what exactly changes when and how, and which files are updated. Also, the information can not be found on one place.
After talking to Zach, he said that daily builds are prices only and do only affect the `AllPrices` file. The weekly builds (no idea when they happen) do update all data and the `AllPrintings` files for example as well.
I also don't know if files like `AllDeckFiles` are updated weekly, too.

**There should be dates next to the different file boxes in the [Compiled](https://mtgjson.com/downloads/compiled/) list maybe...**
The update schedule hint/explanation could be on top of that list as well.

**Comment by staghouse** [comment]
I am all about this but I don't believe we need a dedicated page for a few paragraphs that we can clarify on the homepage. We can combine what is in the Changelog and the homepage and dedicate a header/section for this info (and clean it up) so it will appear in the sidebar as a link.

**Comment by staghouse** [comment]
Also, I think it would be nice to "generally" explain how the service works. We don't have to get in to details but ill propose something to the team for decision.
