### ISSUE TITLE
Add single zip with separate set JSON files

### ISSUE THREAD

**Issue by Didero** [mtgjson/mtgjson-website#34]
V3 had a single zip-file that contained a JSON file for each set, it would be very useful for me if v4 got that too, if it's not too much trouble.
I know there's the [Sets page](https://mtgjson.com/sets.html), where I could download all the sets separately, but that's more cumbersome and I fear also a bit more error-prone. And it may cost you more bandwidth too.
Thanks!

**Comment by ZeldaZach** [comment]
Update: Only .zip seems practical, so that's what it'll be. Don't feel like incorporating tarballs, unless it's really necessary

**Comment by ancestral** [comment]
Link is broken.

**Comment by ZeldaZach** [comment]
Fixed
