### ISSUE TITLE
[Intermittent] On initial load, the header logo is centered when loading version number

### ISSUE THREAD

**Issue by staghouse** [mtgjson/mtgjson-website#345]
### Steps to reproduce

Hard refresh the page

### What is expected?

Logo to be left aligned when content is loading

### What is actually happening?

Center aligned

**Comment by ZeldaZach** [comment]
I've noticed this as well, never thought it was a big deal. Worth a fix if easy

**Comment by staghouse** [comment]
Also only happening on prod so... YAY

**Comment by staghouse** [comment]
No longer seeing this
