### ISSUE TITLE
Global site optimization

### ISSUE THREAD

**Issue by staghouse** [mtgjson/mtgjson-website#354]
After measuring the site score on https://web.dev/measure/ i've noticed a few areas we can improve upon specifically when it comes to image compression and deferring (specifically the homepage is very bad).

The "Time to Interactive" is especially disconcerting but may have to do with resource blocking

**Comment by staghouse** [comment]
Changing images to webp granted us a huge boost in optimization and page load, however Vuepress does not defer or async the bundled js which could be an unfix-able problem in this case. At any rate, we've optimized the site to be roughly 600kb at its worst render of images without cache and only a couple dozen kb at its worst of images with cache

**Comment by staghouse** [comment]
Actually want to keep this open for now as I research upstream changes to Vuepress

**Comment by ZeldaZach** [comment]
Site just deployed
