### ISSUE TITLE
Compiled files on the website are not accessible

### ISSUE THREAD

**Issue by Psykopear** [mtgjson/mtgjson-website#356]
### Steps to reproduce
Download any compiled json (eg: https://www.mtgjson.com/json/SLD.json )

### What is expected?
I should be able to download compiled json files

### What is actually happening?
The server returns `403 Forbidden`

### Other relevant information
It seems to have happened to all the files

**Comment by tooomm** [comment]
Can you access the site?
I had problems opening some subpages. Maybe related

**Comment by Psykopear** [comment]
Yes I can access the site, it's just the links of the compiled sets that return 403.
I also tried with a different connection/ip to be sure I wasn't being throttled or banned by ip for some reason.

**Comment by ZeldaZach** [comment]
Fixed again. The site script had a build error. I'll prob change the build scripts to account for this kind of stuff.
