### ISSUE TITLE
Add Google site verification tag

### ISSUE THREAD

**Issue by staghouse** [mtgjson/mtgjson-website#358]
### Is your feature request related to a problem? Please describe.

Adding the tag allows us to reindex page at will, right now, the website is still index as the old website on google search results

### Describe the solution you'd like

add the meta tag `<meta name="google-site-verification" content="M0vhY1d0DytNcuhlzErPmN1UUXkPEZM_jkj8q_S21JY" />` to the vuepress config as any other meta tag is added

**Comment by ZeldaZach** [comment]
Deployed
