### ISSUE TITLE
Better documentation for AllCards

### ISSUE THREAD

**Issue by CantyCanadian** [mtgjson/mtgjson-website#37]
Been implementing the whole card document inside my software and was setting up the rarity field. However, I realized that it stayed default for every card. That's when I noticed that, in both my .json and the online .json, the field is simply missing. Is that a bug, on purpose or I'm just crazy? I'd like to have rarities to add it as a filter parameter.

**Comment by ancestral** [comment]
I’m thinking of splitting each file into its own page as otherwise the documentation page ends up becoming massive.

**Comment by ericlakatos** [comment]
Possible Solution:

Change the table layout to show all the removed fields at the bottom of he table for AllCards

**Comment by ZeldaZach** [comment]
Might be a good idea. We want to update the entire website to be more user friendly

**Comment by staghouse** [comment]
Dealing with this in a fork, though the solution for documenting the differences is still in progress

**Comment by staghouse** [comment]
AllCards is now updated to reflect only fields shown in AllCards. Deferring closing this for more discussion on if its more clear now.

**Comment by staghouse** [comment]
Closing because of stagnation. If more clarity is needed please open a new ticket.
