### ISSUE TITLE
Download links are down

### ISSUE THREAD

**Issue by madmox** [mtgjson/mtgjson-website#373]
### Steps to reproduce
Go to https://mtgjson.com/downloads/all-files/ and click any download link.

### What is expected?
Should be able to download the files.

### What is actually happening?
The server returns `403 Forbidden`

### Other relevant information
Similar to https://github.com/mtgjson/mtgjson-website/issues/356.

**Comment by ZeldaZach** [comment]
My upload script is still wonky. Will rewrite.
