### ISSUE TITLE
Sets JSON url return Sorry, we can't find this page...

### ISSUE THREAD

**Issue by brunoliveiralcantara** [mtgjson/mtgjson-website#394]
Hi MTG JSON Team!

The website JSON pages are returning a standard error page for content not found.

For example: https://www.mtgjson.com/json/THB.json

**Comment by brunoliveiralcantara** [comment]
Problem solved. Site JSON data 100% back.

**Comment by brunoliveiralcantara** [comment]
I found the problem. URL with non-www works fine, but with www don't works.

Example OK: https://mtgjson.com/json/THB.json
Example NOT OK: https://www.mtgjson.com/json/THB.json

For this reason I reopen this issue.

**Comment by ZeldaZach** [comment]
Both URLs work for me on mobile... try clearing cache?

**Comment by brunoliveiralcantara** [comment]
Thanks @ZeldaZach!

Clearing cache worked fine!
