### ISSUE TITLE
Updates for v5

### ISSUE THREAD

**Issue by staghouse** [mtgjson/mtgjson-website#399]
1. File "types" documentation will get updated with the following data:

`meta: { <meta data reference> },
data: { <actual file data reference > }`

This may get kind of tricky because files themselves often are full of data points - instead of changing the interior data we could apply this info to the parent data structure? Will take some investigation or notation that will be quite different than what we do already.

2. Download links will now follow a versioning "api" schema as such: `mtgjson.com/api/v[number]/files/...` where the documentation only links to the current major supported version. However, we can document how other files are available for v4 still using the old files|json paths and the new schema in order to not break current projects.

**Comment by ZeldaZach** [comment]
This done?

**Comment by staghouse** [comment]
v5 docs are all merged in to master and looking pretty good as far as I can tell.
