### ISSUE TITLE
Unlisted existing Patreon supporter - François Andrieux.

### ISSUE THREAD

**Issue by FrankIsAtank** [mtgjson/mtgjson-website#429]
Thank you for providing this service. I manage my MTG collection using an SQL database which is made possible by the card data you provide.

> Describe the desired name of the supporter as it should appear on the website

François Andrieux is preferred, otherwise Francois Andrieux is acceptable.

> Describe the web URL for this supporter

No URL.

> Provide an image if available for this supporter (at least 200px width or height)

No image.

> If Patreon, describe Tier and start date as "YYYY-MM"

Since 2019-12 at "Uncommon Supporter" (5$ per month).

**Comment by staghouse** [comment]
We currently require an image for every Patron - unless another is provided I will be using your github account image.

Feel free to provide another. It does not have to be of you or anything personal.

**Comment by ZeldaZach** [comment]
Also, thanks for supporting our work!!

**Comment by FrankIsAtank** [comment]
I do not own the rights to the image I use for my github profile, so I'm not sure you would be allowed to use it on your site.

Would the following image work for you? I own the rights to it and grant permission to use it and to resize or crop it as you see fit for this purpose.

![jsonmtg portrait](https://user-images.githubusercontent.com/66426225/83904226-7bc38700-a72d-11ea-9579-b005bda77335.png)

**Comment by staghouse** [comment]
I will make that work. Thanks for providing!
