### ISSUE TITLE
Missing fields in Card (Token) documentation

### ISSUE THREAD

**Issue by krijoh92** [mtgjson/mtgjson-website#443]
### Steps to reproduce
Read the [documentation](https://mtgjson.com/data-models/card-token/) on token cards, download a [set file](https://mtgjson.com/api/v5/M13.json) with tokens and compare.

### What is expected?
Documentation to say card tokens have the following fields:
- availability
- frameVersion
- hasFoil
- hasNonFoil
- identifiers
- isReprint
- promoTypes

### What is actually happening?
Documentation does not mention the fields mentioned

**Comment by krijoh92** [comment]
I'll submit a PR asap 👍

**Comment by ZeldaZach** [comment]
Thanks for your help making MTGJSON the best service possible for our customers :)
