### ISSUE TITLE
Missing fields/attributes on fields in documentation

### ISSUE THREAD

**Issue by krijoh92** [mtgjson/mtgjson-website#446]
### Steps to reproduce
Analyse all set and deck files and all card/token objects within them

### What is expected?
Documentation to correctly reflect data structure in JSON files 

### What is actually happening?
Documentation almost correctly reflects data structure in JSON files, my findings below:

#### Card properties:
Missing property:

- isFoil (I think it's only used in deck files, but should still be represented on the Card data-model)

Should be optional properties

- faceConvertedManaCost
- manaCost

Should be token properties:

- edhrecRank
- flavorText
- frameEffects
- isFullArt
- isPromo
- keywords

#### Set properties:
Missing:

- isNonFoilOnly (should also be optional)

**Comment by staghouse** [comment]
@ZeldaZach Can you confirm the above is true?

**Comment by krijoh92** [comment]
I got a set with that property. I can doublecheck which set had it in a bit and post my findings ✌️

**Comment by staghouse** [comment]
Thanks. Please distinguish between a full Set and a SetList "Set", otherwise known as a manifest

**Comment by krijoh92** [comment]
Yeah, I downloaded each and everyone one of the Set files individually and got this attribute on them.

Affected Set files:
https://mtgjson.com/api/v5/HTR.json
https://mtgjson.com/api/v5/HTR17.json
https://mtgjson.com/api/v5/ALL.json
https://mtgjson.com/api/v5/ATH.json
https://mtgjson.com/api/v5/ATQ.json
https://mtgjson.com/api/v5/ARN.json
https://mtgjson.com/api/v5/ARC.json
https://mtgjson.com/api/v5/OARC.json
https://mtgjson.com/api/v5/E01.json
https://mtgjson.com/api/v5/OE01.json
https://mtgjson.com/api/v5/PARL.json
https://mtgjson.com/api/v5/XANA.json
https://mtgjson.com/api/v5/PALP.json
https://mtgjson.com/api/v5/PAST.json
https://mtgjson.com/api/v5/PSS1.json
https://mtgjson.com/api/v5/BRB.json
https://mtgjson.com/api/v5/TBTH.json
https://mtgjson.com/api/v5/THP2.json
https://mtgjson.com/api/v5/PCEL.json
https://mtgjson.com/api/v5/CHR.json
https://mtgjson.com/api/v5/6ED.json
https://mtgjson.com/api/v5/CST.json
https://mtgjson.com/api/v5/CED.json
https://mtgjson.com/api/v5/CMD.json
https://mtgjson.com/api/v5/C13.json
https://mtgjson.com/api/v5/C14.json
https://mtgjson.com/api/v5/C15.json
https://mtgjson.com/api/v5/PLGM.json
https://mtgjson.com/api/v5/TDAG.json
https://mtgjson.com/api/v5/PDRC.json
https://mtgjson.com/api/v5/TD2.json
https://mtgjson.com/api/v5/PDP12.json
https://mtgjson.com/api/v5/PELP.json
https://mtgjson.com/api/v5/EXO.json
https://mtgjson.com/api/v5/E02.json
https://mtgjson.com/api/v5/TFTH.json
https://mtgjson.com/api/v5/FEM.json
https://mtgjson.com/api/v5/5ED.json
https://mtgjson.com/api/v5/FBB.json
https://mtgjson.com/api/v5/4ED.json
https://mtgjson.com/api/v5/4BB.json
https://mtgjson.com/api/v5/GNT.json
https://mtgjson.com/api/v5/PGRU.json
https://mtgjson.com/api/v5/PHUK.json
https://mtgjson.com/api/v5/PHPR.json
https://mtgjson.com/api/v5/HA1.json
https://mtgjson.com/api/v5/PHJ.json
https://mtgjson.com/api/v5/HML.json
https://mtgjson.com/api/v5/PIDW.json
https://mtgjson.com/api/v5/PI13.json
https://mtgjson.com/api/v5/PI14.json
https://mtgjson.com/api/v5/ICE.json
https://mtgjson.com/api/v5/CEI.json
https://mtgjson.com/api/v5/ITP.json
https://mtgjson.com/api/v5/JMP.json
https://mtgjson.com/api/v5/L12.json
https://mtgjson.com/api/v5/L13.json
https://mtgjson.com/api/v5/L14.json
https://mtgjson.com/api/v5/L15.json
https://mtgjson.com/api/v5/LEG.json
https://mtgjson.com/api/v5/LEA.json
https://mtgjson.com/api/v5/LEB.json
https://mtgjson.com/api/v5/PPC1.json
https://mtgjson.com/api/v5/TD0.json
https://mtgjson.com/api/v5/PR2.json
https://mtgjson.com/api/v5/P03.json
https://mtgjson.com/api/v5/PMIC.json
https://mtgjson.com/api/v5/MIR.json
https://mtgjson.com/api/v5/PBOK.json
https://mtgjson.com/api/v5/MD1.json
https://mtgjson.com/api/v5/AMH1.json
https://mtgjson.com/api/v5/MGB.json
https://mtgjson.com/api/v5/MB1.json
https://mtgjson.com/api/v5/CMB1.json
https://mtgjson.com/api/v5/HOP.json
https://mtgjson.com/api/v5/PC2.json
https://mtgjson.com/api/v5/OPC2.json
https://mtgjson.com/api/v5/PCA.json
https://mtgjson.com/api/v5/OPCA.json
https://mtgjson.com/api/v5/OHOP.json
https://mtgjson.com/api/v5/POR.json
https://mtgjson.com/api/v5/PPOD.json
https://mtgjson.com/api/v5/P02.json
https://mtgjson.com/api/v5/PTK.json
https://mtgjson.com/api/v5/PTC.json
https://mtgjson.com/api/v5/PHOP.json
https://mtgjson.com/api/v5/PARC.json
https://mtgjson.com/api/v5/PRED.json
https://mtgjson.com/api/v5/REN.json
https://mtgjson.com/api/v5/3ED.json
https://mtgjson.com/api/v5/RIN.json
https://mtgjson.com/api/v5/RQS.json
https://mtgjson.com/api/v5/PSAL.json
https://mtgjson.com/api/v5/PS11.json
https://mtgjson.com/api/v5/PSDG.json
https://mtgjson.com/api/v5/S99.json
https://mtgjson.com/api/v5/STH.json
https://mtgjson.com/api/v5/SUM.json
https://mtgjson.com/api/v5/PTKDF.json
https://mtgjson.com/api/v5/TMP.json
https://mtgjson.com/api/v5/DRK.json
https://mtgjson.com/api/v5/THP1.json
https://mtgjson.com/api/v5/UGIN.json
https://mtgjson.com/api/v5/UGL.json
https://mtgjson.com/api/v5/2ED.json
https://mtgjson.com/api/v5/USG.json
https://mtgjson.com/api/v5/PVAN.json
https://mtgjson.com/api/v5/VIS.json
https://mtgjson.com/api/v5/WTH.json
https://mtgjson.com/api/v5/W16.json
https://mtgjson.com/api/v5/W17.json
https://mtgjson.com/api/v5/WC97.json
https://mtgjson.com/api/v5/WC98.json
https://mtgjson.com/api/v5/WC99.json
https://mtgjson.com/api/v5/WC00.json
https://mtgjson.com/api/v5/WC01.json
https://mtgjson.com/api/v5/WC02.json
https://mtgjson.com/api/v5/WC03.json
https://mtgjson.com/api/v5/WC04.json

**Comment by krijoh92** [comment]
I compiled the above list from code that downloaded each Set file and checked which of themcontained the "isNonFoilOnly" attribute on the data object. The code did not distinguish from that attribute being true or false, just checked if it existed or not.

**Comment by staghouse** [comment]
Thanks for the confirmation. Ill get this updated to Set

**Comment by krijoh92** [comment]
I can submit a PR with the fixed for all fields mentioned in the original issue description, if you want me to.

And no problem, happy to help!

**Comment by staghouse** [comment]
Already on it as a part of something else. Thanks though!
