### ISSUE TITLE
Download card list specific to gaming system

### ISSUE THREAD

**Issue by sam1el** [mtgjson/mtgjson-website#461]
### Is your feature request related to a problem? Please describe.
Not related to a bug

### Describe the solution you'd like
 I'd like to be able to download files based on criteria such as 
*  Only whats available in MTGA
*  Only what's available in Magic the Gathering online
*  Etc. 

### Describe, if any, alternatives you've considered
Considered loading into a local db and editing out anything not wanted

### Additional context
I'm looking to create some side projects with the info you have available but want to make them specific for the gaming platform. I did look through the docs but, couldn't find a solid answer

**Comment by staghouse** [comment]
CC: @ZeldaZach, this seems like something we would have as an output file

**Comment by ZeldaZach** [comment]
You can use the `availability` tag, which shows arena, mtgo, paper, etc. I see no need for a separate file in this instance.
