### ISSUE TITLE
New "Powered by" item: Booster Box Simulator

### ISSUE THREAD

**Issue by aprct** [mtgjson/mtgjson-website#462]
### Is your feature request related to a problem? Please describe.
No.

### Describe the solution you'd like
Please add "Booster Box Simulator" to the "Powered by" section of the home page.

### Describe, if any, alternatives you've considered
N/A

### Additional context
Link: https://www.mtgboxsim.com
Name: Booster Box Simulator
Icon: [https://www.mtgboxsim.com/images/mtgboxsim-icon.png](https://www.mtgboxsim.com/images/mtgboxsim-icon.png) (transparent) or [https://www.mtgboxsim.com/images/mtgboxsim-icon-filled.png](https://www.mtgboxsim.com/images/mtgboxsim-icon-filled.png) (filled)

**Comment by staghouse** [comment]
Done. Awaiting build
