### ISSUE TITLE
Language Strings Differ from Documentation

### ISSUE THREAD

**Issue by nickhrsn** [mtgjson/mtgjson-website#49]
#### Description of Bug:

The documentation states the range of values for `language` in `foreignData` as including:
"Portuguese", "Simplified Chinese", and "Traditional Chinese"

The values in `AllSets.json` are actually:
"Portuguese (Brazil)", "Chinese Simplified", and "Chinese Traditional"

**Comment by staghouse** [comment]
Addressed in new site

**Comment by tooomm** [comment]
See https://github.com/mtgjson/mtgjson-website/issues/9#issuecomment-463177905

**Comment by staghouse** [comment]
@nickhrsn Please confirm your change is now live on production and accurate. Thanks!

**Comment by nickhrsn** [comment]
@staghouse Yep, the docs are now accurate to the data.

P.S. Great job on the new site, looks great 👍

**Comment by ZeldaZach** [comment]
Glad you like! Please feel free to let us know of any feedback so we can continue to improve :)
