### ISSUE TITLE
Fetchbot Sorter Missing from the MTGJSON main sight as a patreon supporter.

### ISSUE THREAD

**Issue by FetchbotSorter** [mtgjson/mtgjson-website#491]
Hi, I am donating to the MTGJSON Project, but I don't show up as a Patreon Supporter.

Can you add me?  Thanks!

You guys are the best!

Darren Davison

**Comment by staghouse** [comment]
Hello, could you please provide more detail such as

- What level supporter you are
- A url to your project
- An avatar to use
