### ISSUE TITLE
Incorrect or missing fields in documentation

### ISSUE THREAD

**Issue by patrickgaskill** [mtgjson/mtgjson-website#499]
MTGJSON version: 5.1.0+20210614

I caught some issues while defining and validating schemas using the documentation, starting from the file model for Card (Atomic).

ForeignData
- `faceName` should be marked as optional

Identifiers
- `scryfallId` should be marked as optional

Legalities
- `gladiator` is missing from docs
- `oldschool` is missing from docs
- `premodern` is missing from docs

Card (Atomic)
- `colorIndicator` should be marked as optional
- `uuid` should be marked as optional

**Comment by staghouse** [comment]
can you provide the legalities of Sol Ring as it pertains to those missing formats?

**Comment by patrickgaskill** [comment]
Sure, from [Scryfall](https://api.scryfall.com/cards/4cbc6901-6a4a-4d0a-83ea-7eefa3b35021?format=json&pretty=true):

```
"gladiator": "not_legal",
"oldschool": "not_legal",
"premodern": "not_legal"
```

**Comment by patrickgaskill** [comment]
The missing uuid issue appears to just be this one card in AtomicCards.json:
```
[
  {
    "colorIdentity": ["G", "R"],
    "colors": ["G", "R"],
    "convertedManaCost": 6.0,
    "foreignData": [],
    "identifiers": {
      "scryfallOracleId": "a2c5ee76-6084-413c-bb70-45490d818374"
    },
    "layout": "normal",
    "legalities": {},
    "manaCost": "{2}{R}{R}{G}{G}",
    "name": "\"Ach! Hans, Run!\"",
    "printings": ["UNH"],
    "purchaseUrls": {
      "cardKingdom": "https://mtgjson.com/links/84dfefe718a51cf8",
      "cardKingdomFoil": "https://mtgjson.com/links/d8c9f3fc1e93c89c",
      "cardmarket": "https://mtgjson.com/links/b9d69f0d1a9fb80c",
      "tcgplayer": "https://mtgjson.com/links/c51d2b13ff76f1f0"
    },
    "rulings": [],
    "subtypes": [],
    "supertypes": [],
    "text": "At the beginning of your upkeep, you may say \"Ach! Hans, run! It's the . . .\" and the name of a creature card. If you do, search your library for a card with that name, put it onto the battlefield, then shuffle. That creature gains haste. Exile it at the beginning of the next end step.",
    "type": "Enchantment",
    "types": ["Enchantment"]
  }
]
```

**Comment by patrickgaskill** [comment]
When validating SetList.json, I found a couple more things:

- the values for items in `translations` should be marked optional

- there is an optional `sealedProduct` object that is missing from the docs. I'm validating it like this:
`sealed_product: Optional[list[MtgjsonSealedProduct]]`

```
class MtgjsonSealedProduct:
    Schema: ClassVar[Type[Schema]] = Schema
    identifiers: dict[str, str]
    name: str
    purchase_urls: dict[str, str]
    release_date: Optional[str]
    uuid: str
```
