### ISSUE TITLE
Caret icon update for toggling options

### ISSUE THREAD

**Issue by tooomm** [mtgjson/mtgjson-website#505]
### Please describe the issue
The "arrow" icon next to the `Toggle Options` menu is different to how it's usually utilized.

Can be seen on https://mtgjson.com/downloads/all-sets/ for example:
- collapsed:
![toggle1](https://user-images.githubusercontent.com/9874850/130363133-8e23e596-e147-4ecd-9bdc-0a4614a0c85e.png)
- opened:
![toggle2](https://user-images.githubusercontent.com/9874850/130363135-eef9ecbe-84d4-4019-bcba-1f1dfe19d874.png)

Default usage would be to have the caret point to the right when folded. MTGJSON have it point up.
When opened and all options are available, it correctly points down.

### Describe the solution you'd like
Use `caret-right` icon for the folded options view: https://fontawesome.com/v5.15/icons/caret-right?style=solid

**Comment by staghouse** [comment]
Fixed

**Comment by tooomm** [comment]
Looks great!
