### ISSUE TITLE
Question: Thoughts on adding Sass

### ISSUE THREAD

**Issue by staghouse** [mtgjson/mtgjson-website#51]
The code would be cleaner to maintain and the infra shouldn't be too difficult to put in place as there's a python library already.

Instead of running pelican directly via CLI maybe it would be wrapped around a bash in addition to the Sass compiler?

**Comment by ZeldaZach** [comment]
Would love some help improving the website. Open to PRs

**Comment by ericlakatos** [comment]
As per Discord, going to invest some time in a logic, simple static website with traditional web languages and easy data structures for updating as needed

**Comment by staghouse** [comment]
Dealing with this in a fork
