### ISSUE TITLE
Website: GUI must able to open direct download link for sets instead download

### ISSUE THREAD

**Issue by JayDi85** [mtgjson/mtgjson-website#510]
There were a regress from last website updates: now all direct download links hides under popup menu (example: [sets list](https://mtgjson.com/downloads/all-sets/)).
![shot_211127_215149](https://user-images.githubusercontent.com/8344157/143691744-659bc103-1ac6-4032-ba42-b2a678caf1f0.png)

It's a fail -- I can't open json from a browser any more (firefox) -- it require to download it instead. Please return old link type or button/link to open it.

**Comment by staghouse** [comment]
This is not a regression but an enhancement. Most JSON files are too large and will often cause a browser tab or browser window to hang or crash. I do not suggest going back to the old way.

**Comment by JayDi85** [comment]
> Most JSON files are too large and will often cause a browser tab or browser window to hang or crash

I used Firefox to open it as formatted and searchable source. Single sets and decks are small and workable.

**Comment by staghouse** [comment]
I can look in to only making the larger data downloadable and keep the smaller ones openable

**Comment by ZeldaZach** [comment]
@JayDi85 You can download the JSON file and then view it in Firefox to use the JSON Browser UI

**Comment by staghouse** [comment]
Closing as this is not viable cross browser without substantial work for an edge case. As Zach stated, once you select the file to download you should be prompted to open it in a browser.
