### ISSUE TITLE
Description of Side field is misleading

### ISSUE THREAD

**Issue by zqft9001** [mtgjson/mtgjson-website#514]
The description for the side field reads as follows:

"The identifier of the card side. Used on cards with multiple faces."

This is misleading as there are cards with multiple printed faces in the same set that are not dual faced cards, and this field does not account for those (e.x. Icatian Javelineers' Fallen Empires printings, B.F.M, Sly Spy). It does however account for cards with aftermath and other split cards, in addition to DFCs.

Proposed new description:

"The identifier of the card side. Used on cards with multiple faces on the same card."

The current description can be found in the below:

https://mtgjson.com/data-models/card-atomic/#side
https://mtgjson.com/data-models/card-token/#side
https://mtgjson.com/data-models/card-deck/#side
https://mtgjson.com/data-models/card-set/#side

**Comment by aaronmallen** [comment]
Thanks @zqft9001

**Comment by staghouse** [comment]
Deployed
