### ISSUE TITLE
use common date format

### ISSUE THREAD

**Issue by tooomm** [mtgjson/mtgjson-website#54]
On the start page there is a date given for the latest update/version.
It sais `2019 January 30` which is a very unusual way of writing a date I think?

Use the international shortform `2019-01-30` or `30th January 2019` (UK) / `January 30, 2019` (US) instead?

**Comment by ZeldaZach** [comment]
Cosmetic and shouldn't be used by any programs. It gets the job done imo

**Comment by staghouse** [comment]
Irrelevant with new site. Do we want to add the latest version build back to the homepage?

**Comment by ZeldaZach** [comment]
Would like to have it, yeah. My thought is the upper left corner and it should just say
`MTGJSON v4.3.0`

**Comment by ancestral** [comment]
*Year Month Day* is how computers does it (and Japan, too).

**Comment by staghouse** [comment]
Closing. See #71 for more discussion relating to navbar versioning. Also see #76 PR for current implementation.
