### ISSUE TITLE
Typos, undocumented fields and incorrectly documented fields.

### ISSUE THREAD

**Issue by JochemKuijpers** [mtgjson/mtgjson-website#595]
### Location of update needed
On several model pages. I'll list them per item.

### What does the documentation look like?
See below.

### What should the documentation look like?
By data model page:

**ForeignData**
- In the `types` member description, there's a small typo that says 'subtypesa' instead of 'subtypes'. On other pages this is correct.

**Booster**
- There's a duplicated 'and' (as in: 'and and') in a comment of the `cards` field.
- There are two undocumented fields in the `sheets` objects: `fixed` and `allowDuplicates`, both are seen in the AllPrintings data, set to `true` when present. It's not clear to me what their documentation should be.

**Legalities**
- Fields are missing from the documentation but are seen in the AllPrintings data: `oathkeeper` and `paupercommander`.

**Set**
- A field is not marked as optional, but it is not always seen in the AllPrintings data: `language`. (it's not present on e.g. the "PARC" set, which contains no cards. May be a data error?)

**Card (Set)**
- A field is not marked as optional, but it is not always seen in the AllPrintings data: `relatedCards`.
- A field is missing from the documentation but seen in the AllPrintings data: `duelDeck` (note: it has been documented for **Card (Deck)**).

**Card (Token)**
- A field is not marked as optional, but it is not always seen in the AllPrintings data: `relatedCards`.
- Fields are missing from the documentation but seen in the AllPrintings data: `originalText`, `originalType`, `isTextless` (note: these are documented for **Card (Set)**).
- A field is documented but never seen in the AllPrintings data: `loyalty`.

### Additional context
I've posted about these findings in the #documentation Discord channel as well. Feel free to reach out to me there or here for more information if necessary.

**Comment by JochemKuijpers** [comment]
I've updated the issue and removed this:

> **PurchaseUrls**
> - A field is missing from the documentation but seen in the AllPrintings data: `cardKingdom`.

This actually wasn't an issue, I just missed the first line in the TypeScript signature when copying the data.

**Comment by staghouse** [comment]
I'm not going to have time soon to fix these issues. Any help is appreciated.
