### ISSUE TITLE
AllPrintings compressed SQL databases links are dead

### ISSUE THREAD

**Issue by gitrid** [mtgjson/mtgjson-website#597]
### Steps to reproduce
1. Go to https://mtgjson.com/downloads/all-files/
2. Select AllPrintings.sql.gz from drop-down list
or simply click that:
https://mtgjson.com/api/v5/AllPrintings.sql.gz
### What is expected?
A compressed database.
### What is actually happening?
File doesn't exist.
### Additional context
Uncompressed files seem to be fine.

**Comment by ZeldaZach** [comment]
I've been playing around with the MTGSQLive repo and today's build had some issues with these files. I manually uploaded the non-compressed versions. This should be addressed with tomorrow's build. I do apologize for the issue!
