### ISSUE TITLE
Override keyrune.css generic icon

### ISSUE THREAD

**Issue by staghouse** [mtgjson/mtgjson-website#61]
keyrune.css is used to apply icons to sets and uses a generic icon for sets that has no icon/or accurate icon. Find a way to override this.

**Comment by staghouse** [comment]
Logic for this exists in a sense that if a set has a parentCode, then that set with a global set id will activate keyrune using the parent set code.

Will keep open until this feature is released.

**Comment by staghouse** [comment]
Update: feature has been released but further complexity from #88 prevents the data from populating.

Will be addressed after.

**Comment by ZeldaZach** [comment]
Seems do-able now
