### ISSUE TITLE
please add Mana Pool to supporters list

### ISSUE THREAD

**Issue by andrewljohnson** [mtgjson/mtgjson-website#631]
### The desired name of the supporter as it should appear on the website

ManaPool.com

### The web URL for this supporter (if applicable)

https://manapool.com

### An image for this supporter at least 200px width or height (if applicable)

![logo](https://github.com/mtgjson/mtgjson-website/assets/455551/e6fcfd5f-810d-48c8-bf5c-64d608def8cb)

### If a Patron, the tier and start date as "YYYY-MM"

We became a support via GitHub on 2024-03

**Comment by staghouse** [comment]
Hi @andrewljohnson , as a Patreon supporter are you in the uncommon, rare or mythic tier?

**Comment by andrewljohnson** [comment]
mythic

--Andrew

**Comment by ZeldaZach** [comment]
I do apologize for the delay @andrewljohnson we'll get this up shortly

cc @staghouse

**Comment by andrewljohnson** [comment]
@ZeldaZach @staghouse I wanted to check in on this, do you think we'll be included in the list soon?
