### ISSUE TITLE
Missing Identifiers in `cards` table from AllPrintings.sql

### ISSUE THREAD

**Issue by ivysmnope** [mtgjson/mtgjson-website#639]
Hi, I tried to use the mysql file of AllPrintings and noticed it didn't match what was written in the documentation, I'm not sure if this is a problem on my side and I did something wrong and how to fix it.
In the mtgjson repo the readme said to come here for anything unclear about the documentation so I hope this is the right place.

### Steps to reproduce
1. Download the `All Printings.sql` from the download page
2. Import mysql database (I used XAMPP's phpmyadmin)

### What is expected?
the `cards` table should have the `identifier` field as it should follow the Card (Set) model as written in the documentation

### What is actually happening?
the `cards` table does not have the `identifier` field

### Additional context
I checked the sql file I downloaded and the `identifier` field was not there
I tried to download it again but it was still missing

Thank you

**Comment by zqft9001** [comment]
The SQL versions of the files are laid out a bit differently than the JSON, and the documentation doesn't reflect that. My understanding is it's being worked on. 

The cards table contains uuid, which you can use to join it with the cardIdentifiers table on `cards.uuid = cardIdentifiers.uuid`

**Comment by ivysmnope** [comment]
thank you that really confused me if they're working on it then that's great
that was very helpful thank you
have a nice day
