### ISSUE TITLE
Undocumented property "battle" in CardTypes data model

### ISSUE THREAD

**Issue by grim7reaper** [mtgjson/mtgjson-website#640]
### Location of update needed

[`CardTypes`](https://mtgjson.com/data-models/card-types/) data model

### What does the documentation look like?

The [`CardTypes`](https://mtgjson.com/downloads/all-files/#cardtypes) JSON file contains a field `battle` which is not represented in the current documentation of the [`CardTypes`](https://mtgjson.com/data-models/card-types/) data model.

### What should the documentation look like?

Add the field in the type:

```js
battle: CardType;
```

and the relevant documentation:

```md
battle

The battle type of a card.

- Type: `CardType`
- Introduced: `v4.0.0`
```
(not 100% sure about the `Introduced: v4.0.0`, I just copy-pasted from the other fields

### Additional context

I'm using MTGJSON 5.2.2+20240814

**Comment by ZeldaZach** [comment]
Added
