### ISSUE TITLE
A non-documented identifiers fields seems to have superseded `multiverseId` in Foreign Data data model

### ISSUE THREAD

**Issue by grim7reaper** [mtgjson/mtgjson-website#641]
### Location of update needed

[Foreign Data](https://mtgjson.com/data-models/foreign-data/)

### What does the documentation look like?

The documentation mentions an optional `multiverseId` property, but in the CardAtomic models it's never set.
Instead, I'm seeing an `identifiers` property that seems to supersedes this one.

### What should the documentation look like?

Remove the `multiverseId` or at least mark it as deprecated?
Documente the `identifiers` property?

### Additional context

So far I've only checked:
- AtomicCards.json
- ModernAtomic.json
- PauperAtomic.json
- PioneerAtomic.json
- StandardAtomic.json
- VintageAtomic.json

So I'm not sure if it's widespread or only limited to the `CardAtomic` model.
I'm using MTGJSON 5.2.2+20240814

---

Edit: in some `CardDeck` I've found card with both fields actually.
Exemple from `TimeyWimey_WHO.json`:

```json
{
  "foreignData": [
    {
      "identifiers": {
        "multiverseId": 634410,
        "scryfallId": "de240e5f-6038-44b0-bfe0-44b1d7b2ddfe"
      },
      "language": "German",
      "multiverseId": 634410,
      "name": "Der Zehnte Doctor",
      "type": "Legendäre Kreatur — Time-Lord, Doctor"
    },
    {
      "identifiers": {
        "multiverseId": 634414,
        "scryfallId": "3367e74c-daef-4a75-af10-4ca0cb85cad9"
      },
      "language": "French",
      "multiverseId": 634414,
      "name": "Le Dixième Docteur",
      "type": "Créature légendaire : time lord et docteur"
    },
    {
      "identifiers": {
        "multiverseId": 634418,
        "scryfallId": "e050c0bb-47a4-4ad3-9b97-3e9c5066e7b1"
      },
      "language": "Japanese",
      "multiverseId": 634418,
      "name": "10代目ドクター",
      "type": "伝説のクリーチャー — タイムロード・ドクター"
    }
  ],
  "name": "The Tenth Doctor",
  "uuid": "10bc8c49-2239-58ec-92a8-9ccb9298331f"
}
```

**Comment by ZeldaZach** [comment]
Fixed!
