### ISSUE TITLE
Non-documented property "etched" in SourceProducts data model

### ISSUE THREAD

**Issue by grim7reaper** [mtgjson/mtgjson-website#643]
### Location of update needed

[`SourceProducts`](https://mtgjson.com/data-models/source-products/) data model

### What does the documentation look like?

Only `foil` and `nonfoil` properties are documented, but some instance also have an `etched` property.
For instance in `FlashyFliers_MOM.json`:

```json
{
  "finishes": [
    "nonfoil",
    "foil",
    "etched"
  ],
  "name": "Opt",
  "setCode": "STA",
  "sourceProducts": {
    "etched": [
      "52fca41e-cac5-5eb2-b107-0164e829d064"
    ],
    "foil": [
      "141e45d1-be58-5312-82ad-3cd774a567cb",
      "52fca41e-cac5-5eb2-b107-0164e829d064",
      "64143552-b778-5cdb-a29f-af955ef626e8",
      "7a22deb5-1740-5a47-af47-dcdc175c4b77",
      "b18d1de8-64f5-5aa6-bfd1-638520cc9c28"
    ],
    "nonfoil": [
      "141e45d1-be58-5312-82ad-3cd774a567cb",
      "64143552-b778-5cdb-a29f-af955ef626e8",
      "7a22deb5-1740-5a47-af47-dcdc175c4b77",
      "b18d1de8-64f5-5aa6-bfd1-638520cc9c28"
    ]
  },
  "uuid": "9f35aba6-72d9-565b-bb8b-2ba628282b2e"
}
```

### What should the documentation look like?

Add the field in the type:

```js
etched?: string[];
```

and the relevant documentation:

```md
etched

A list of universal unique identifiers (v5) generated by MTGJSON for the [Sealed Product](https://mtgjson.com/data-models/sealed-product/) the etched card is found in.

- Type: `string[]`
- Introduced: `v5.2.2`
```
(not 100% sure about the `Introduced: v5.2.2`, I just copy-pasted from the other fields

### Additional context

I'm using MTGJSON 5.2.2+20240814

---

Also since we're talking about `SourceProducts`, I think the `foil`/`nonfoil` property should also be optional, no?

**Comment by ZeldaZach** [comment]
Agreed, thanks for the fix!
