### ISSUE TITLE
Non-documented property "sealedProductUuids" in Deck data model

### ISSUE THREAD

**Issue by grim7reaper** [mtgjson/mtgjson-website#644]
### Location of update needed

[`Deck`](https://mtgjson.com/data-models/deck/) data model

### What does the documentation look like?
No mention of a `sealedProductUuids` but I can see it in JSON file, for instance in `AzaarLichlord_PAST.json`:

```json
{
  "meta": {
    "date": "2024-08-15",
    "version": "5.2.2+20240815"
  },
  "data": {
    "code": "PAST",
    "commander": [],
    "mainBoard": [...],
    "name": "Azaar Lichlord",
    "releaseDate": "1997-04-01",
    "sealedProductUuids": null,
    "sideBoard": [],
    "type": "Shandalar Enemy Deck"
  }
}

```

### What should the documentation look like?

Not sure since the value is `null` I don't know what's supposed to be here.

### Additional context

 I'm using MTGJSON 5.2.2+20240814

**Comment by ZeldaZach** [comment]
@axxroytovu What's this field for?

**Comment by axxroytovu** [comment]
It's a cross reference identifying which sealed products contain this deck.

**Comment by ZeldaZach** [comment]
Addressed
