### ISSUE TITLE
Non-documented `name` property in `BoosterConfig` data model

### ISSUE THREAD

**Issue by grim7reaper** [mtgjson/mtgjson-website#649]
### Location of update needed

[BoosterConfig](https://mtgjson.com/data-models/booster/booster-config/) data model

### What does the documentation look like?

No `name` property visible in the documentation.
But some `BoosterConfig` from `AllPrintings.json` have one, for example:

```json
"10E": {
  "baseSetSize": 383,
  "block": "Core Set",
  "booster": {
    "draft": {
      "boosters": []
      "boostersTotalWeight": 2401000,
      "name": "Tenth Edition Draft Booster",
      "sheets": {}
    }
  },
}
```

### What should the documentation look like?

Add documentation for a `name?: string` property

### Additional context

I'm using MTGJSON 5.2.2+20240816

**Comment by ZeldaZach** [comment]
Done
