### ISSUE TITLE
Property `relatedCards` should me marked as optional in CardDeck

### ISSUE THREAD

**Issue by grim7reaper** [mtgjson/mtgjson-website#650]
### Location of update needed

https://mtgjson.com/data-models/card/card-deck/

### What does the documentation look like?

```js
  relatedCards: RelatedCards;
```

### What should the documentation look like?

```js
  relatedCards?: RelatedCards;
```

### Additional context

Example from `AzaarLichlord_PAST.json`:
```json
{
  "name": "Swamp",
  "number": "298",
  "originalType": "Land",
  "rarity": "common",
  "setCode": "3ED",
  "uuid": "798c0707-56a8-531b-b1ed-9e9c675271db",
}
```

**Comment by ZeldaZach** [comment]
Done
