### ISSUE TITLE
Issues with CardSet data model

### ISSUE THREAD

**Issue by grim7reaper** [mtgjson/mtgjson-website#652]
#### Version(s) tested against

MTGJSON 5.2.2+20240816

#### Description of Bug

I've found the following mismatches between the documentation of CardSet and the
data in `AllIdentifiers.json`

- Property `finishes` seems optional
    - e.g. `Sigardian Evangel` (UUID `6e637182-ea65-538b-b738-8a8275364b02`) doesn't have it.
- Properties `legalities`, `purchaseUrls` and `rarity` seems to be optional (card token?) as well
    - e.g. `Inkling` (UUID `00093ed9-5b6b-5a88-bd12-7c3e260abf1c`) doesn't have them.
- Presence of a non-documented `orientation` property
    - e.g. `Path to the World Tree // Path to the World Tree` (UUID `000c1d56-5114-574a-a834-9f1c9a20ebe3`) has it.
- Presence of a non-documented `reverseRelated` property
    - e.g. `Inkling` (UUID `00093ed9-5b6b-5a88-bd12-7c3e260abf1c`) has it.

**Comment by ZeldaZach** [comment]
I've done some cleanup based on this. Lmk if you spot any other issues!
