### ISSUE TITLE
who we serve - image issues

### ISSUE THREAD

**Issue by tooomm** [mtgjson/mtgjson-website#68]
- `DideRobot` uses a github logo
Should be removed and listed down with the other "no logo" services

- `MagicFetchBot` has no logo
Should be listed down with the other "no logo" services

A hint below the trable that the list is "Sorted alphabetically with all icons first" would be nice, too.

**Comment by ZeldaZach** [comment]
Update your cache this changed 2 days ago

**Comment by tooomm** [comment]
You are right!
