### ISSUE TITLE
MTGJSON logo usage

### ISSUE THREAD

**Issue by ZeldaZach** [mtgjson/mtgjson-website#71]
Replace the MTGJSON in the top left with the MTGJSON logo, and on the landing page remove the "About MTGJSON" header and the logo. Will free up more space on the homepage.

**Comment by staghouse** [comment]
Requires ejecting theme, adding it to the repo with full control over layout.

In the long run this will be better for us but keep in mind the `/theme` folder will now be present in the project using non-Pug templates

**Comment by staghouse** [comment]
Addressed in #76
