### ISSUE TITLE
Add sorting options for Individual Deck downloads

### ISSUE THREAD

**Issue by staghouse** [mtgjson/mtgjson-website#78]
Add sorting to the Individual Decks download page for filtering pre-constructed decks.

Functionality exists for Individual Sets already, perhaps turn this in to a helper.

**Comment by tooomm** [comment]
There is only the possibility to order the list of individual sets, no filtering or searching yet.

That should be available on both subpages for sets and decks. 👍

**Comment by ZeldaZach** [comment]
Wrong ticket tom. See #63

**Comment by tooomm** [comment]
I'm just pointing out that

>Add filtering to the Individual Decks download page...
>...**Functionality exists for Individual Sets already**

is not true.

**Comment by staghouse** [comment]
Correct. Updated ticket for accuracy.
