### ISSUE TITLE
Anchor links on changelog do not always scroll to accurate position

### ISSUE THREAD

**Issue by staghouse** [mtgjson/mtgjson-website#84]
1. The anchors for headline release do not have enough spacing to accommodate the fixed navigation which can cause, in part, this issue.
2. Investigate he simple smooth-scroll capability. Removing its current implementation may resolve this.

**Comment by staghouse** [comment]
There is currently no possible solution for keeping smooth scroll + keeping anchor tags all presented in the changelog.

Read through the warnings of [this](https://bit.ly/2Hs1fq6) to see why.

We can, however, disable smooth scrolling for the time being to keep anchor link integrity.

**Comment by ZeldaZach** [comment]
I like smooth scrolling. Also, that URL is dead.

**Comment by staghouse** [comment]
Link updated. TL;DR, we might have to handle the changelog differently or reformat the heading styling. Would require some experimentation at this point is all.

**Comment by staghouse** [comment]
This is a thing with limited support: https://css-tricks.com/fixed-headers-on-page-links-and-overlapping-content-oh-my/

**Comment by staghouse** [comment]
After further investigation this is a problem also assisted by the way we automatically "documentize" a markdown changelog:

When anchoring to a headline the page expects the previous anchor to be out of view. Because the changelog markdown is not directly markup, there is no way to target the section/headline in CSS and add more spacing intelligently and with regard to any and all future markdown formatting.

Further investigation is warranted.

**Comment by staghouse** [comment]
Final thoughts and then im closing this ticket because its stale and the conditions are no longer as accurate:

This is unfixable as long as we have a fixed navigation. There is, to my knowledge, in Vuepress and all browsers a way to win this battle.
