### ISSUE TITLE
set page: improve with filter/search etc.

### ISSUE THREAD

**Issue by tooomm** [mtgjson/mtgjson-website#9]
~~I think it would be more helpful if the set order at https://mtgjson.com/v4/sets.html would be reversed and shows the newest sets on top instead oldest.~~ #12

Random thought:
Having order buttons, a filter/search (e.g. for set properties) or a timeline and group the sets by year etc. are several other ideas to improve the presentation and make it easier to access the information on that page.

**Comment by ZeldaZach** [comment]
I like the idea. It's a static site, which makes it a bit trickier, but maybe there's something we can play around with

**Comment by tooomm** [comment]
Initial request with reordering is done in https://github.com/mtgjson/mtgjson4-website/pull/12

Do we want to keep this open + rename the heading to keep track of a more advanced rework with smarter search/filter capabilities at a later point?

**Comment by ancestral** [comment]
Sure.

I’m okay spending some time to find a good JS library for potentially handing this. I have become a bit busier; Tuesday’s I’ll have a little time to play around, but I am absolutely open to someone else taking it on if they are interested.

**Comment by ZeldaZach** [comment]
Recommendation given:
put them in a table and slap a datatable on top
https://datatables.net/

**Comment by ZeldaZach** [comment]
https://codesandbox.io/s/0y87kpv5rn

**Comment by ericlakatos** [comment]
Considering the above is React is the consideration a full fledged JS web application?

**Comment by staghouse** [comment]
This is being handled in the new website that uses Vue. The feature is already finished.

**Comment by tooomm** [comment]
Which new website? @staghouse

**Comment by ZeldaZach** [comment]
@tooomm Stag is working on a new site, it's secretive for now. Stay tuned.

**Comment by tooomm** [comment]
>This is being handled in the new website that uses Vue. The feature is already finished.

There is a search missing.
However, I like the several filter options for ordering in the dropdown now!

Very nice new webpage in general!!

**Comment by staghouse** [comment]
Search is a bit of an issue we are doing discovery on with https://community.algolia.com/docsearch/

Closing this and opened a new enhancement ticket to address this directly at #63
